### ISSUE TITLE
 Improvement  ideas

### ISSUE THREAD

**Issue by alafad** [eliasthecactus/plexer#2]
Hello eliasthecactus, i found your project, because plexripper has a few problem like a OOM error while downloading a few things .

Now i have a found your pretty cool app is it possible to bulk download a TVshow with one click (all Episodes and Seasons).

Another cool feature would be great, if I can create a watchlist in the original Plex app and the downloader will download from these.

Thanks you

**Comment by eliasthecactus** [comment]
hello alafad
yes of course. this will be a festure. i started the project like one week ago so it will take another two weeks till i will release the 1.0-alpha. please check the project again in a few days.
have a nice weekend:)

**Comment by alafad** [comment]
This sound really good, i`ve read your noxbot readme  will that project continued in this repo and would that work without any costs?

Sorry for my many questions, im really intrested.

**Comment by eliasthecactus** [comment]
PlexGet will be opensource and free forever. but i won’t continue on the noxBot project.

**Comment by alafad** [comment]
Now I understand it, i thougt the knoxbot will now maintained in this repo.

My questions about the costs was related for the external services, but you will have your reasons for archive this repo.

Which Plexservers  could you recommend, i can recommend this one https://www.reddit.com/r/SharePLEX/comments/x014ta/free_german_content_invite_only_discord_1080p_4k/

**Comment by eliasthecactus** [comment]
i use okcool: https://www[dot]okcool[dot]stream/index.php?rp=/store/plex

i use it every second month to download the latest movies and tv shows so i pay $5/month.

the reason why i created the new project was bc i realized nox[dot]to is slowly dying and i don‘t want to search a new site esch time and create a new tool. and bc there always will be a plex share i choose plex:)

**Comment by panzli** [comment]
Hey Elias, der Plex share Anbieter sieht gut aus, könnte ich mich bei dir mal einen Monat mit einklinken, gerne schicke ich dir auch 5€.

Gruß
