### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by DebeshMishra** [eliasthecactus/plexer#4]
It just says wrong credentials even though they are correct.

**Comment by alafad** [comment]
Hey @DebeshMishra  have you tried Login with your Username or Email?

If tested the Login with https://download-from-plex.duckdns.org/ and it works for me...

**Comment by DebeshMishra** [comment]
@alafad Tried it, just says wrong credentials.

**Comment by eliasthecactus** [comment]
@alafad do you have 2FA enabled?

**Comment by DebeshMishra** [comment]
@eliasthecactus If you meant me, 2FA is enabled yes.

**Comment by eliasthecactus** [comment]
@DebeshMishra yes, that's the problem... disable it or create an app password if possible

**Comment by DebeshMishra** [comment]
> @DebeshMishra yes, that's the problem... disable it or create an app password if possible

That's a problem though, I shouldn't have to disable 2FA to get it to work because of the security risk. What's an app password?

**Comment by eliasthecactus** [comment]
> > @DebeshMishra yes, that's the problem... disable it or create an app password if possible
> 
> That's a problem though, I shouldn't have to disable 2FA to get it to work because of the security risk. What's an app password?

Sometimes you can create app passwords for third party applications which you can use to bypass 2fa. i don't know if thats the case for plex. i don't have a solution for this right now... maybe i can take a look into it over christmas.
